### PR TITLE
feature: Support for Anthropic on Vertex AI

### PR DESCRIPTION
**Pull request by marshmellow77**
This PR adds support for [Anthropic Claude models via Google Vertex AI](https://cloud.google.com/vertex-ai/generative-ai/docs/partner-models/use-claude).

**Example:**
```
python launch_scientist.py --model "vertex_ai/claude-3-5-sonnet@20240620" \
                           --experiment nanoGPT_lite \
                           --num-ideas 2
```

Note that this PR also directs Aider queries to Vertex AI via [LiteLLM for Vertex AI](https://litellm.vercel.app/docs/providers/vertex#anthropic).

### CODE REVIEW

**Comment by marshmellow77** [comment]
Any blockers on merging this PR? Anything I can help with?

**Comment by marshmellow77** [comment]
@conglu1997 - Any blockers on merging this PR? Anything I can help with?

**Comment by conglu1997** [comment]
Hi! I think many merge conflicts now, would you be able to help resolve?

**Comment by marshmellow77** [comment]
sure, let me resolve the conflicts and get back to you once done, thanks

**Comment by marshmellow77** [comment]
@conglu1997  - I created a new PR: https://github.com/SakanaAI/AI-Scientist/pull/49 without conflicts.

**Pull request closed without merging**
