### PR TITLE
Add Computer Vision Classification Template with MobileNetV3 Baseline

### PR DESCRIPTION
**Pull request by j-cunanan**
## Overview
This pull request introduces a new template for computer vision classification tasks, along with a strong baseline implementation using MobileNetV3. The additions have been thoroughly tested end-to-end to ensure reliability and ease of use.

### Key Features
1. **CV Classification Template**: A reusable template for computer vision classification tasks, promoting consistency and efficiency in future projects.

2. **MobileNetV3 Baseline**: Implementation of a strong baseline model using MobileNetV3, known for its efficiency and performance in various computer vision applications.

3. **End-to-End Testing**: Comprehensive testing to validate the entire pipeline from data input to model output.

### Technical Details
- model is based on pytorch implementation (https://github.com/pytorch/vision/blob/main/torchvision/models/mobilenetv3.py#L117) and could load pre-trained weights if needed.

### Sample paper outputs
[adaptive_channel_thresholding_mobilenetv3.pdf](https://github.com/user-attachments/files/17404983/adaptive_channel_thresholding_mobilenetv3.pdf)
[mb4-pre.pdf](https://github.com/user-attachments/files/17404990/mb4-pre.pdf)

I welcome any feedback or suggestions for improvement. Please let me know if you need any additional information or clarification.

### CODE REVIEW

**Comment by Tylersuard** [comment]
Thank you for creating this.

Are you giving your LLM access to modify your experiment.py file?

Can you please walk me through the steps you used to create your own experiment? The repo maintainers are not being helpful.

**Comment by conglu1997** [comment]
Thanks so much for the contribution - could you remove the changes to the README and follow the current style, the template.tex file should have more appropriate base cites. There is also an incorrect modification to the nanogpt ideas.

**Comment by j-cunanan** [comment]
Thanks for the feedback @conglu1997 !
I've modified based on your suggestions above. Let me know if there's anything else I should change :)

**Comment by BradKML** [comment]
@conglu1997 I am starting to think that there needs to be a prompt meta-template that allows people to, through dialogue, vaguely hint at which piece of research they would like to pursue, and provide example papers (e.g. DOI/ArXiv links) so that it understands, and fetch the relevant GitHub repo by itself.

**Pull request merged**
